name: Main

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]

jobs:
  main:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

  test:
    uses: ./.github/workflows/python-test.yml

  build:
    needs: test
    uses: ./.github/workflows/docker-image.yml