name: Python test module

on:
  workflow_call:

  workflow_dispatch:

jobs:

  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test module
      run: |
        SEY_USERNAME=${{secrets.SEY_USERNAME}} SEY_PASSWORD=${{secrets.SEY_PASSWORD}} SEY_ELECTRICAL_CONTRACT_ID=${{secrets.SEY_ELECTRICAL_CONTRACT_ID}} SEY_WATER_CONTRACT_ID=${{secrets.SEY_WATER_CONTRACT_ID}} python -m unittest discover -v
